# ===============================================================
# Random Module
# ===============================================================
def random_module():
    import random
    # import my_module

    # random_integer = random.randint(1,10)
    # print(random_integer)
    #
    # # Module
    # print(my_module.my_favorite_number)
    #
    # random_number_0_to_1 = random.random()
    # print(random_number_0_to_1)

    # random_float = random.uniform(1,10)
    # print(random_float)

    random_heads_or_tails = random.randint(0,1)
    if random_heads_or_tails == 0:
        print("Heads")
    else:
        print("Tails")
random_module()


"""
Pseudorandom Number Generators
Computers are not random, because they are built with circuits and switches. But randomness is very important when building software, especially games. It would be really boring if every move in a video game was pre-determined.

So, some computer scientists invented pseudorandom number generators. e.g. https://en.wikipedia.org/wiki/Mersenne_Twister

If you want to learn more about pseudorandom number generators, I recommend watching this video by Khan Academy: https://www.youtube.com/watch?v=GtOt7EBNEwQ&ab_channel=KhanAcademyLabs

The Random module in Python
Read the docs here: https://docs.python.org/3/library/random.html

To use it you need to first import it:

import random

Random Whole Numbers Within a Range
import random
rand_num = random.randint(1, 10)

#This will produce a random whole number between 1 and 10 (inclusive).
Modules in Python
Python allows us to put code into different files and import that code if needed. This means that we can better organise and modularise our code.

You can create a new module simply by creating a new .py file, and then you can import variables or functions from that file just by using the import keyword.

Random Floats
You can generate a random number between 0.0 (inclusive) and 1.0 (not inclusive) using the following code from the random module:

import random
rand_num_0_to_1 = random.random()
It can also be represented like this

0.0 <= random.random() < 1.0

You can expand the range of random numbers generated by this method using multiplication.

e.g. random.random() * 5

Will generate a random number between 0 and 5.

Another way to generate random floating point numbers is to use the uniform() function.

import random
random_float = random.uniform(1, 10)
#This will generate a random floating point number between 1 and 10. 
This method may or may not include the upper bound depending on the rounding of the floating point number. So it's best represented as:

a <= random.uniform(a,b) <= b

So depending on if you want the upper bound included you will choose whether to use random.random() or random.uniform().

PAUSE 1 - Heads or Tails
Create a coin flip program using what you have learnt about randomisation in Python. It should randomly print "Heads" or "Tails" everytime it is run.

 Hint 
"""

# ===============================================================
# List of States
# ===============================================================
def list_of_states():
    states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts",
                        "Maryland", "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina",
                        "Rhode Island", "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana",
                        "Mississippi", "Illinois", "Alabama", "Maine", "Missouri", "Arkansas", "Michigan",
                        "Florida", "Texas", "Iowa", "Wisconsin", "California", "Minnesota", "Oregon", "Kansas",
                        "West Virginia", "Nevada", "Nebraska", "Colorado", "North Dakota", "South Dakota",
                        "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma", "New Mexico", "Arizona",
                        "Alaska", "Hawaii"]
    print(states_of_america[0])

    states_of_america[1] = "Pencilvania"

    states_of_america.append("Frankland")

    # states_of_america.extend("")
    print(states_of_america)
list_of_states()

"""
You can create a simple collection of ordered items using a Python list. e.g.

fruits = ["Cherry", "Apple", "Pear"]

or

states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts", "Maryland", "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina", "Rhode Island", "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi", "Illinois", "Alabama", "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas", "Iowa", "Wisconsin", "California", "Minnesota", "Oregon", "Kansas", "West Virginia", "Nevada", "Nebraska", "Colorado", "North Dakota", "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma", "New Mexico", "Arizona", "Alaska", "Hawaii"]

Accessing Items in Lists
You can provide the name of the list then a square bracket and then the item index that you want. e.g.

states_of_america[0]

will give you "Delaware".

Remember that everything computer related, the first number we count with is 0 and never 1. 0, 1, 2, 3 instead of 1, 2, 3 4.

Negative Indices
You can access items in the list counting from the end of the list by using negative whole numbers. e.g.

fruits = ["Cherry", "Apple", "Pear"]
fruits[-1] #this will be "Pear"
Modifying Items
You can use the same syntax to get hold of items in a List to modify it. e.g.

fruits = ["Cherry", "Apple", "Pear"]
fruits[0] = "Orange"
# fruits will now become ["Orange", "Apple", "Pear"]
Adding Items
You can add items to the end of a List using the append() function. e.g.

fruits = ["Cherry", "Apple", "Pear"]
fruits.append("Orange")
# fruits will now become ["Cherry", "Apple", "Pear", "Orange"]
Lists Documentation
You can find the documentation for Python Lists and other List related functions here: https://docs.python.org/3/tutorial/datastructures.html
"""

# ===============================================================
# List Funtions extend() and append()
# ===============================================================

"""
In Python, append() and extend() are both used to add elements to a list, 
but they handle the input differently. 

1. append() - Adds a Single Object 
The append() method adds its argument as a single new element at the end of the list. 

Argument: Any object (number, string, list, etc.).
Result: The list length increases by exactly 1.
Nesting: If you append a list, it becomes a nested list inside the original. 
"""

x = [1, 2, 3]
x.append([4, 5])
# Result: [1, 2, 3, [4, 5]]
# Use code with caution.

"""
2. extend() - Adds Multiple Elements 
The extend() method iterates over its argument and adds each item individually to the end of the list. 

Argument: Must be an iterable (list, tuple, string, set).
Result: The list length increases by the number of items in the iterable.
Nesting: It "flattens" the input, merging the elements into the original list
"""
x = [1, 2, 3]
x.extend([4, 5])
# Result: [1, 2, 3, 4, 5]

# Similarly (+= Operator (In-place Extend))
# y = [4, 5]
# x =+ y
# Result: [1, 2, 3, 4, 5] 


# ===============================================================
# Banker Roulette
# ===============================================================
def banker_roulette():
    import random
    friends = ["Alice", "Bob", "Charlie", "David", "Emanuel"]

    # random.randint
    list_len = len(friends)
    rand = random.randint(0,list_len)
    print(friends[rand])

    # random.choice
    print(random.choice(friends))
banker_roulette()

"""
Figure out how to pick a random name from the list of friends.

 Hint 1 
There are two ways of doing this and they are equally valid.
 Hint 2 
Think about how you can generate random number to use an index to pick out items from the List.
 Hint 3 
Alternatively think about using the documentation to figure out how to get a random item from a List in Python.
"""

# ===============================================================
# Index Error (Array Out of Bound Error)
# ===============================================================
def index_error():
    # states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts", "Maryland",
    #                      "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina", "Rhode Island",
    #                      "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi", "Illinois",
    #                      "Alabama", "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas", "Iowa", "Wisconsin",
    #                      "California", "Minnesota", "Oregon", "Kansas", "West Virginia", "Nevada", "Nebraska", "Colorado",
    #                      "North Dakota", "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma",
    #                      "New Mexico", "Arizona", "Alaska", "Hawaii"]
    #
    # print(states_of_america)
    #
    # list_len = len(states_of_america) # 50 -> 49
    # print(states_of_america[len(states_of_america) - 1])

    # dirty_dozen = ["Strawberries", "Spinach", "Kale", "Nectarines", "Apples", "Grapes", "Tomatoes", "Peaches",
    #                "Celery", "Cherries", "Potatoes", "Pears"]

    fruits = ["Strawberries", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears"]
    vegetables = ["Spinach", "Kale", "Tomatoes", "Celery", "Potatoes"]

    # Nested list
    dirty_dozen = [fruits, vegetables]
    print(dirty_dozen)
index_error()

"""
Length of List
You can get the length of a list (number of items in the list) or the length of a string (number characters in the string) by using the len() function. https://docs.python.org/3/library/functions.html#len

IndexError
When you try to access an item that is not in the range of the List, you will get an IndexError. e.g.

fruits = ["Cherry", "Apple", "Pear"]
print(fruits[3]) #This will be an IndexError
Nested Lists
You can put Lists inside other Lists, this becomes something called a "Nested List" or a "2D List". e.g.

fruits = ["Cherry", "Apple", "Pear"]
veg = ["Cucumber", "Kale", "Spinnach"]
fruits_and_veg = [fruits, veg]
#The list would look like this: [["Cherry", "Apple", "Pear"], ["Cucumber", "Kale", "Spinnach"]]
You could also represent the list in 2D format like this:

["Cherry", "Apple", "Pear"]
["Cucumber", "Kale", "Spinnach"]
"""

# ===============================================================
# RPS (Rock, Paper, Scissors) Project
# ===============================================================
def rock_paper_scissors():
    import random

    rock = '''
        _______
    ---'   ____)
            (_____)
            (_____)
            (____)
    ---.__(___)
    '''

    paper = '''
        _______
    ---'   ____)____
              ______)
                _______)
                _______)
    ---.__________)
    '''

    scissors = '''
        _______
    ---'    ____)____
                 ______)
            __________)
         (____)
    ---.__(___)
    '''

    rps = [rock, paper, scissors]
    user = int(input("What do you choose? Type 0 for Rock, 1 for Paper, 2 for Scissors: \n"))

    if user < 0 or user > 2:
        print("Invalid choice")
    else:
        computer = random.randint(0, 2)
        print("You chose: ")
        print(rps[user])
        print("Computer chose: ")
        print(rps[computer])

        if user == computer:
            print("It's a Draw")
        elif (user == 0 and computer == 2) or \
            (user == 1 and computer == 0) or \
            (user == 2 and computer == 1):
            print("You win!")
        else:
            print("You lose")
rock_paper_scissors()


# ===============================================================
# Optimized version of RPS (Rock, Paper, Scissors) Project
# ===============================================================

import random

def rock_paper_scissors():

    rps = [
        '''
        _______
    ---'   ____)
          (_____)
          (_____)
          (____)
    ---.__(___)
        ''',

        '''
        _______
    ---'   ____)____
              ______)
              _______)
             _______)
    ---.__________)
        ''',

        '''
        _______
    ---'   ____)____
              ______)
           __________)
          (____)
    ---.__(___)
        '''
    ]

    user = int(input("Type 0 for Rock, 1 for Paper, 2 for Scissors: "))

    if user not in [0, 1, 2]:
        print("Invalid choice")
        return

    computer = random.choice([0, 1, 2])

    print("You chose:")
    print(rps[user])

    print("Computer chose:")
    print(rps[computer])

    if user == computer:
        print("Draw")
    elif (user - computer) % 3 == 1:
        print("You Win!")
    else:
        print("You Lose!")


rock_paper_scissors()