name: ISS Pass Alert Daily Python Script

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-projects/iss-pass-alert

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script 
        env:
            MY_EMAIL: ${{secrets.MY_EMAIL}}
            MY_EMAIL_PASSWORD: ${{secrets.MY_EMAIL_PASSWORD}}
        run: python main.py
