name: Rain Alert SMS Daily Python Script

on:
  schedule:
    # 7:00 AM IST is 1:30 AM UTC
    - cron: '30 1 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-projects/rain-alert-SMS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pip install requests flask twilio

      - name: Run Python script 
        env:
            WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
            TWILIO_SID: ${{ secrets.TWILIO_SID }}
            TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
            VIRTUAL_TWILIO_NUMBER: ${{ secrets.VIRTUAL_TWILIO_NUMBER }}
            VERIFIED_NUMBER: ${{ secrets.VERIFIED_NUMBER }}
            EMAIL_ID: ${{secrets.EMAIL_ID}}
            EMAIL_ID_PASSWORD: ${{secrets.EMAIL_ID_PASSWORD}}
        run: python main.py
