name: TrackARP Daily Check Workflow

on:
  schedule:
    # 06:00 IST = 00:30 UTC
    - cron: '30 0 * * *'

  # Allows you to run the workflow manually
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    defaults:
      run:
        working-directory: projects/track_arp

    steps:

      # ------------------------------------------------------
      # Checkout Repository
      # ------------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v5

      # ------------------------------------------------------
      # Set up Python
      # ------------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      # ------------------------------------------------------
      # Install Dependencies
      # ------------------------------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ------------------------------------------------------
      # Run Python Script
      # ------------------------------------------------------
      - name: Run Python script
        env:
          # Email
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          EMAIL_ID_PASSWORD: ${{ secrets.EMAIL_ID_PASSWORD }}
          EMAIL_PROVIDER_SMTP_ADDRESS: ${{ secrets.EMAIL_PROVIDER_SMTP_ADDRESS }}

          # Telegram
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: python main.py
        run: python test_connection.py
